name: Dependency scan

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Go Dependency Submission
        uses: actions/go-dependency-submission@v1
        
